/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wearqxztlaochpanckhq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYXJxeHp0bGFvY2hwYW5ja2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NDkwOTEsImV4cCI6MjA4NzEyNTA5MX0.Wq37laxBwedNrYWjzW4RzaChf-9srrcpLSm-N8A5AVQ"